force-app/main/default/objects/Store_Supply_Order__c/Store_Supply_Order__c.object-meta.xml
<CustomObject>
    <label>Store Supply Order</label>
    <nameField>
        <label>Store Supply Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Store Supply Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Store_Supply_Order__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <label>Supplier</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Store Supply Orders</relationshipLabel>
    <relationshipName>Store_Supply_Orders</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/StoreSupplyOrderTriggerHandler.cls
public with sharing class StoreSupplyOrderTriggerHandler {
  @TestVisible
  private static Map<String, Object> flowVariableMap = new Map<String, Object>();
  /**
   * @description - Finds suppliers on new Orders and sends them an email
   * @param newOrders - List of newly created store supply order records
   */

  public static void handleAfterInsert(List<Store_Supply_Order__c> newOrders) {
    Set<Id> supplierIds = new Set<Id>();
    for (Store_Supply_Order__c storeOrder : newOrders) {
      supplierIds.add(storeOrder.Supplier__c);
    }

    //Get the suppliers of these Ordears
    List<Account> supplierList = [
      SELECT Name, Primary_Email_Contact__c
      FROM Account
      WHERE Id IN :supplierIds
    ];
    sendEmails(supplierList);
  }

  /**
   * @descrption - Calls a flow to email the suppliers
   * @param suppliers - List of Supplier accounts to email
   */
  private static void sendEmails(List<Account> suppliers) {
    flowVariableMap.put('supplierList', suppliers);
    Flow.Interview.New_Order_Email_to_Supplier sendEmailFlow = new Flow.Interview.New_Order_Email_to_Supplier(
      flowVariableMap
    );
    sendEmailFlow.start();
  }
}