force-app/main/default/objects/Retail_Store__c/Retail_Store__c.object-meta.xml
<CustomObject>
    <label>Retail Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Retail Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Retail_Store__c/fields/Buzz_Id__c.field-meta.xml
<CustomField>
    <fullName>Buzz_Id__c</fullName>
    <description>External Id which refers to the data from Buzz System</description>
    <externalId>true</externalId>
    <label>Buzz Id</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Retail_Store__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>City in which the Retail Store is Located in.</description>
    <label>City</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Exceptions.cls
public with sharing class Exceptions {
  public virtual class MyRetailStoreException extends Exception {
  }

  public class RetailException extends MyRetailStoreException {
  }

  /**
   * @description - Method to create a Retail Store
   * @param storeName Name of the Retail Store to create
   * @param throwException Boolean specifying whether or not to throw an Exception
   **/
  public static void createRetailStore(
    String storeName,
    Boolean throwException
  ) {
    Retail_Store__c store = new Retail_Store__c(
      Name = storeName,
      City__c = 'Rourkela',
      Buzz_Id__c = '1247T'
    );
    try {
      if (throwException) {
        throw new RetailException('A jubilant retail error message');
      }
      insert store;
    } catch (DMLException de) {
      System.debug(
        'I caught a DML exception with message:- ' +
          de.getMessage() +
          ' caused by ' +
          de.getStackTraceString()
      );
    } catch (MyRetailStoreException e) {
      System.debug(
        'I caught another Exception:- ' +
          e.getTypeName() +
          ' with message ' +
          e.getMessage()
      );
    }
  }
}