force-app/main/default/objects/Customer_Feedback__c/Customer_Feedback__c.object-meta.xml
<CustomObject>
    <label>Customer Feedback</label>
    <nameField>
        <displayFormat>FEED-{0000}</displayFormat>
        <label>Customer Feedback Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Feedbacks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Retail_Store__c/Retail_Store__c.object-meta.xml
<CustomObject>
    <label>Retail Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Retail Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Retail_Store__c/fields/Buzz_Id__c.field-meta.xml
<CustomField>
    <fullName>Buzz_Id__c</fullName>
    <description>External Id which refers to the data from Buzz System</description>
    <externalId>true</externalId>
    <label>Buzz Id</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Retail_Store__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>City in which the Retail Store is Located in.</description>
    <label>City</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Retail_Store__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Malaysia</fullName>
            </value>
            <value>
                <fullName>Singapore</fullName>
            </value>
            <value>
                <fullName>South Korea</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Retail_Store__c/fields/Customer_Feedback__c.field-meta.xml
<CustomField>
    <fullName>Customer_Feedback__c</fullName>
    <label>Feedback Rating</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Poor</fullName>
            </value>
            <value>
                <fullName>Moderate</fullName>
            </value>
            <value>
                <fullName>Good</fullName>
            </value>
            <value>
                <fullName>Excellent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestFactory.cls
/**
 * @description - Test Factory to create commonly used data for testers
 */
@isTest
public with sharing class TestFactory {
  /**
   * @description - Create Retail Test Stores
   * @param  storeToCreate - The number of test stores to create
   * @param performDML - Determines whether or not DML should fire or not
   * @return - List of stores for Testing
   */
  public static List<Retail_Store__c> createRetailStores(
    Integer storeToCreate,
    Boolean performDML
  ) {
    List<Retail_Store__c> newRetailStores = new List<Retail_Store__c>();
    for (Integer i = 0; i < storeToCreate; i++) {
      Retail_Store__c storeRec = new Retail_Store__c();
      storeRec.Name = 'Pune Hub ' + (i + 1);
      storeRec.Customer_Feedback__c = 'Good';
      storeRec.City__c = 'Pune';
      storeRec.Country__c = 'India';
      storeRec.Buzz_Id__c = 'TESTBUZZ' + (i + 1);
      newRetailStores.add(storeRec);
    }
    if (performDML) {
      Database.insert(newRetailStores, false);
    }
    return newRetailStores;
  }

  /**
   * @description - Create a test user
   * @param profileName - The number of the profile the test user should have
   * @return New User for Testing
   */
  public static User createUser(String profileName) {
    Profile userProfile = [SELECT Id FROM Profile WHERE Name = :profileName];
    User testUser = new User(
      FirstName = 'Super',
      LastName = 'Tester',
      profileId = userProfile.Id,
      Email = 'stester@terrified.com',
      Username = 'stester@terrified.com',
      CompanyName = 'Rathindra and Co.',
      Title = 'Awesome Tester',
      Alias = 'stester',
      TimeZoneSidKey='Asia/Kolkata',
      LocaleSidKey='en_IN',
      EmailEncodingKey='UTF-8',
      LanguageLocaleKey='en_US'
    );
    return testUser;
  }
}